"""Add custom screener indicators

Revision ID: 14474a7beda6
Revises: c85e71d74bc3
Create Date: 2026-05-13 16:12:41.003690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14474a7beda6'
down_revision = 'c85e71d74bc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_results_scan_date'), table_name='scan_results')
    op.create_index(op.f('ix_scan_results_scan_date'), 'scan_results', ['scan_date'], unique=False)
    op.add_column('stock_metrics', sa.Column('sma50', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('sma150', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('sma200', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('perf_1y', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('perf_1w', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('low_52w', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('adr_percent', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('avg_volume_10d', sa.Integer(), nullable=True))
    op.add_column('stock_metrics', sa.Column('current_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_metrics', 'current_price')
    op.drop_column('stock_metrics', 'avg_volume_10d')
    op.drop_column('stock_metrics', 'adr_percent')
    op.drop_column('stock_metrics', 'low_52w')
    op.drop_column('stock_metrics', 'perf_1w')
    op.drop_column('stock_metrics', 'perf_1y')
    op.drop_column('stock_metrics', 'sma200')
    op.drop_column('stock_metrics', 'sma150')
    op.drop_column('stock_metrics', 'sma50')
    op.drop_index(op.f('ix_scan_results_scan_date'), table_name='scan_results')
    op.create_index(op.f('ix_scan_results_scan_date'), 'scan_results', ['scan_name', 'scan_date'], unique=False)
    # ### end Alembic commands ###
