"""Add Universe Engine tables

Revision ID: add_universe_engine
Revises: fd96cdc8cb5a
Create Date: 2026-05-19 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_universe_engine'
down_revision = 'fd96cdc8cb5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # InstrumentIdentity table
    op.create_table('instrument_identities',
    sa.Column('internal_id', sa.String(length=36), nullable=False),
    sa.Column('current_symbol', sa.String(length=10), nullable=False),
    sa.Column('historical_symbols', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('primary_exchange', sa.String(length=50), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('internal_id')
    )
    op.create_index('ix_instrument_identities_current_symbol', 'instrument_identities', ['current_symbol'], unique=False)
    op.create_index('ix_instrument_identities_lifecycle_state', 'instrument_identities', ['lifecycle_state'], unique=False)
    op.create_index('ix_instrument_identities_asset_type', 'instrument_identities', ['asset_type'], unique=False)
    
    # ListingEvent table
    op.create_table('listing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_symbol', sa.String(length=10), nullable=True),
    sa.Column('new_symbol', sa.String(length=10), nullable=True),
    sa.Column('old_exchange', sa.String(length=50), nullable=True),
    sa.Column('new_exchange', sa.String(length=50), nullable=True),
    sa.Column('old_sector', sa.String(length=100), nullable=True),
    sa.Column('new_sector', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listing_events_instrument_id', 'listing_events', ['instrument_id'], unique=False)
    op.create_index('ix_listing_events_event_date', 'listing_events', ['event_date'], unique=False)
    op.create_index('ix_listing_events_event_type', 'listing_events', ['event_type'], unique=False)
    
    # UniverseEnrichment table
    op.create_table('universe_enrichment',
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('float_shares', sa.Integer(), nullable=True),
    sa.Column('avg_volume_20d', sa.Integer(), nullable=True),
    sa.Column('avg_dollar_volume_20d', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('atr_percent', sa.Float(), nullable=True),
    sa.Column('volatility_profile', sa.String(length=50), nullable=True),
    sa.Column('institutional_quality_score', sa.Float(), nullable=True),
    sa.Column('rs_baseline_spy', sa.Float(), nullable=True),
    sa.Column('rs_baseline_qqq', sa.Float(), nullable=True),
    sa.Column('tradability_score', sa.Float(), nullable=True),
    sa.Column('market_cap_tier', sa.String(length=50), nullable=True),
    sa.Column('last_enriched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_index('ix_universe_enrichment_sector', 'universe_enrichment', ['sector'], unique=False)
    op.create_index('ix_universe_enrichment_market_cap_tier', 'universe_enrichment', ['market_cap_tier'], unique=False)
    
    # UniverseTier table
    op.create_table('universe_tiers',
    sa.Column('instrument_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('institutional_quality_score', sa.Float(), nullable=True),
    sa.Column('leadership_score', sa.Float(), nullable=True),
    sa.Column('setup_quality_score', sa.Float(), nullable=True),
    sa.Column('sector_relevance_score', sa.Float(), nullable=True),
    sa.Column('regime_alignment_score', sa.Float(), nullable=True),
    sa.Column('requires_realtime', sa.Boolean(), nullable=False),
    sa.Column('requires_websocket', sa.Boolean(), nullable=False),
    sa.Column('requires_deep_analysis', sa.Boolean(), nullable=False),
    sa.Column('requires_setup_analysis', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.create_index('ix_universe_tiers_tier', 'universe_tiers', ['tier'], unique=False)
    op.create_index('ix_universe_tiers_priority_score', 'universe_tiers', ['priority_score'], unique=False)
    
    # DiscoveryCandidate table
    op.create_table('discovery_candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('discovery_data', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('added_to_universe', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discovery_candidates_symbol', 'discovery_candidates', ['symbol'], unique=False)
    op.create_index('ix_discovery_candidates_trigger', 'discovery_candidates', ['trigger'], unique=False)
    op.create_index('ix_discovery_candidates_processed', 'discovery_candidates', ['processed'], unique=False)
    op.create_index('ix_discovery_candidates_discovered_at', 'discovery_candidates', ['discovered_at'], unique=False)
    
    # UniverseHealthAlert table
    op.create_table('universe_health_alerts',
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_universe_health_alerts_severity', 'universe_health_alerts', ['severity'], unique=False)
    op.create_index('ix_universe_health_alerts_alert_type', 'universe_health_alerts', ['alert_type'], unique=False)
    op.create_index('ix_universe_health_alerts_resolved', 'universe_health_alerts', ['resolved'], unique=False)
    op.create_index('ix_universe_health_alerts_created_at', 'universe_health_alerts', ['created_at'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index('ix_universe_health_alerts_created_at', table_name='universe_health_alerts')
    op.drop_index('ix_universe_health_alerts_resolved', table_name='universe_health_alerts')
    op.drop_index('ix_universe_health_alerts_alert_type', table_name='universe_health_alerts')
    op.drop_index('ix_universe_health_alerts_severity', table_name='universe_health_alerts')
    op.drop_table('universe_health_alerts')
    
    op.drop_index('ix_discovery_candidates_discovered_at', table_name='discovery_candidates')
    op.drop_index('ix_discovery_candidates_processed', table_name='discovery_candidates')
    op.drop_index('ix_discovery_candidates_trigger', table_name='discovery_candidates')
    op.drop_index('ix_discovery_candidates_symbol', table_name='discovery_candidates')
    op.drop_table('discovery_candidates')
    
    op.drop_index('ix_universe_tiers_priority_score', table_name='universe_tiers')
    op.drop_index('ix_universe_tiers_tier', table_name='universe_tiers')
    op.drop_table('universe_tiers')
    
    op.drop_index('ix_universe_enrichment_market_cap_tier', table_name='universe_enrichment')
    op.drop_index('ix_universe_enrichment_sector', table_name='universe_enrichment')
    op.drop_table('universe_enrichment')
    
    op.drop_index('ix_listing_events_event_type', table_name='listing_events')
    op.drop_index('ix_listing_events_event_date', table_name='listing_events')
    op.drop_index('ix_listing_events_instrument_id', table_name='listing_events')
    op.drop_table('listing_events')
    
    op.drop_index('ix_instrument_identities_asset_type', table_name='instrument_identities')
    op.drop_index('ix_instrument_identities_lifecycle_state', table_name='instrument_identities')
    op.drop_index('ix_instrument_identities_current_symbol', table_name='instrument_identities')
    op.drop_table('instrument_identities')
    
    # ### end Alembic commands ###
