"""Create all tables

Revision ID: c85e71d74bc3
Revises: 
Create Date: 2026-05-13 15:23:13.308655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c85e71d74bc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('scan_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scan_results_scan_date', 'scan_results', ['scan_name', 'scan_date'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_name'), 'scan_results', ['scan_name'], unique=False)
    op.create_index(op.f('ix_scan_results_symbol'), 'scan_results', ['symbol'], unique=False)
    op.create_table('sectors',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('performance_daily', sa.Float(), nullable=True),
    sa.Column('performance_weekly', sa.Float(), nullable=True),
    sa.Column('performance_monthly', sa.Float(), nullable=True),
    sa.Column('rank', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('stock_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('ema50', sa.Float(), nullable=True),
    sa.Column('ema200', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('relative_strength_spy', sa.Float(), nullable=True),
    sa.Column('relative_strength_qqq', sa.Float(), nullable=True),
    sa.Column('distance_to_ema20', sa.Float(), nullable=True),
    sa.Column('distance_to_ema50', sa.Float(), nullable=True),
    sa.Column('distance_to_high_52w', sa.Float(), nullable=True),
    sa.Column('avg_volume_20d', sa.Integer(), nullable=True),
    sa.Column('relative_volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_metrics_date'), 'stock_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_stock_metrics_symbol'), 'stock_metrics', ['symbol'], unique=False)
    op.create_index('ix_stock_metrics_symbol_date', 'stock_metrics', ['symbol', 'date'], unique=True)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_index('ix_stock_prices_symbol_date', 'stock_prices', ['symbol', 'date'], unique=True)
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('is_adr', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index('ix_stocks_industry', 'stocks', ['industry'], unique=False)
    op.create_index('ix_stocks_sector', 'stocks', ['sector'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbols', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlists')
    op.drop_index('ix_stocks_sector', table_name='stocks')
    op.drop_index('ix_stocks_industry', table_name='stocks')
    op.drop_table('stocks')
    op.drop_index('ix_stock_prices_symbol_date', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index('ix_stock_metrics_symbol_date', table_name='stock_metrics')
    op.drop_index(op.f('ix_stock_metrics_symbol'), table_name='stock_metrics')
    op.drop_index(op.f('ix_stock_metrics_date'), table_name='stock_metrics')
    op.drop_table('stock_metrics')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_scan_results_symbol'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_name'), table_name='scan_results')
    op.drop_index('ix_scan_results_scan_date', table_name='scan_results')
    op.drop_table('scan_results')
    # ### end Alembic commands ###
