"""Add fast EMAs and pullback quality metrics

Revision ID: e1bfaf0e72c9
Revises: 14474a7beda6
Create Date: 2026-05-15 08:37:29.864356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1bfaf0e72c9'
down_revision = '14474a7beda6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_metrics', sa.Column('ema9', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('ema21', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('distance_to_ema9', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('distance_to_ema21', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('weekly_tightness', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('weekly_volatility_contraction', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('weekly_trend_quality', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('weeks_in_base', sa.Integer(), nullable=True))
    op.add_column('stock_metrics', sa.Column('pullback_quality_score', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('volume_contraction', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('setup_quality', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_metrics', 'setup_quality')
    op.drop_column('stock_metrics', 'volume_contraction')
    op.drop_column('stock_metrics', 'pullback_quality_score')
    op.drop_column('stock_metrics', 'weeks_in_base')
    op.drop_column('stock_metrics', 'weekly_trend_quality')
    op.drop_column('stock_metrics', 'weekly_volatility_contraction')
    op.drop_column('stock_metrics', 'weekly_tightness')
    op.drop_column('stock_metrics', 'distance_to_ema21')
    op.drop_column('stock_metrics', 'distance_to_ema9')
    op.drop_column('stock_metrics', 'ema21')
    op.drop_column('stock_metrics', 'ema9')
    # ### end Alembic commands ###
