"""add perf_4w and perf_13w columns

Revision ID: fd96cdc8cb5a
Revises: e1bfaf0e72c9
Create Date: 2026-05-15 09:33:15.208320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd96cdc8cb5a'
down_revision = 'e1bfaf0e72c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_results_scan_date'), table_name='scan_results')
    op.create_index('ix_scan_results_scan_date', 'scan_results', ['scan_name', 'scan_date'], unique=False)
    op.add_column('stock_metrics', sa.Column('perf_4w', sa.Float(), nullable=True))
    op.add_column('stock_metrics', sa.Column('perf_13w', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_metrics', 'perf_13w')
    op.drop_column('stock_metrics', 'perf_4w')
    op.drop_index('ix_scan_results_scan_date', table_name='scan_results')
    op.create_index(op.f('ix_scan_results_scan_date'), 'scan_results', ['scan_date'], unique=False)
    # ### end Alembic commands ###
